### ISSUE TITLE
./configure fails after last changes

### ISSUE THREAD

**Issue by fadado** [jqlang/jq#1852]
On 2019-02-27T09:26:56+01:00 and after last commit (3ea0199),
 `./configure --with-oniguruma` fails on fedora 29 . This is the last line generated:

```
checking for Python dependencies... configure: error: 
```

The `Makefile` is not generated...

JJOR

**Comment by muhmuhten** [comment]
--disable-docs is a band-aid. It's looking for pipenv, but probably the autoconf changes weren't made correctly.

**Comment by wtlangford** [comment]
So the issue here is that if you don't have python, you can't run all the tests. Before, if you didn't have ruby, you couldn't run all the tests.

That said, I didn't intend to block you out from doing anything, so let's consider that an autoconf bug (autoconf is _hard_).

Relatedly, I think I'll be making a change to drop `pipenv` as a requirement to make it easier for people to set up.

**Comment by wtlangford** [comment]
Should we consider prebuilding a copy of the mantests in the format jq's test mode wants, so that if someone wants to build and run tests, they can do so without setting up python as required?

**Comment by nicowilliams** [comment]
I'd be ok with that, and with skipping mantest if no Python too.

**Comment by gharris999** [comment]
Fails on Ubuntu 18.04.2 too, even with python installed.

**Comment by pangpangshui** [comment]
`--disable-docs` can be a temporary solution.

**Comment by judavi** [comment]
Fails on RHEL 7.5 too, --disable-docs didn't work
`
[judavi@container jq]$ make
mkdir -p src
  GEN      src/builtin.inc
mkdir -p src
  GEN      src/version.h
make  all-recursive
make[1]: Entering directory `/home/judavi/jq'
Making all in modules/oniguruma
make[2]: Entering directory `/home/judavi/jq/modules/oniguruma'
make[2]: *** No rule to make target `all'.  Stop.
make[2]: Leaving directory `/home/judavi/jq/modules/oniguruma'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/judavi/jq'
`

**Comment by nicowilliams** [comment]
@judavi That's a different issue.  Try `./configure --with-oniguruma=builtin`.

**Comment by nicowilliams** [comment]
Oof, now I get:

```
checking for Python dependencies... An error occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pipenv/patched/safety.zip/urllib3/connectionpool.py", line 346, in _make_request
  File "/usr/local/lib/python3.6/dist-packages/pipenv/patched/safety.zip/urllib3/connectionpool.py", line 850, in _validate_conn
  File "/usr/local/lib/python3.6/dist-packages/pipenv/patched/safety.zip/urllib3/connection.py", line 326, in connect
  File "/usr/local/lib/python3.6/dist-packages/pipenv/patched/safety.zip/urllib3/util/ssl_.py", line 329, in ssl_wrap_socket
  File "/usr/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/lib/python3.6/ssl.py", line 817, in __init__
    self.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 1077, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:830: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pipenv/patched/safety.zip/requests/adapters.py", line 440, in send
  File "/usr/local/lib/python3.6/dist-packages/pipenv/patched/safety.zip/urllib3/connectionpool.py", line 639, in urlopen
  File "/usr/local/lib/python3.6/dist-packages/pipenv/patched/safety.zip/urllib3/util/retry.py", line 357, in increment
  File "/usr/local/lib/python3.6/dist-packages/pipenv/patched/safety.zip/urllib3/packages/six.py", line 686, in reraise
  File "/usr/local/lib/python3.6/dist-packages/pipenv/patched/safety.zip/urllib3/connectionpool.py", line 601, in urlopen
  File "/usr/local/lib/python3.6/dist-packages/pipenv/patched/safety.zip/urllib3/connectionpool.py", line 349, in _make_request
  File "/usr/local/lib/python3.6/dist-packages/pipenv/patched/safety.zip/urllib3/connectionpool.py", line 309, in _raise_timeout
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='pyup.io', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/patched/safety.zip/__main__.py", line 12, in <module>
  File "/usr/local/lib/python3.6/dist-packages/pipenv/patched/safety.zip/click/core.py", line 722, in __call__
  File "/usr/local/lib/python3.6/dist-packages/pipenv/patched/safety.zip/click/core.py", line 697, in main
  File "/usr/local/lib/python3.6/dist-packages/pipenv/patched/safety.zip/click/core.py", line 1066, in invoke
  File "/usr/local/lib/python3.6/dist-packages/pipenv/patched/safety.zip/click/core.py", line 895, in invoke
  File "/usr/local/lib/python3.6/dist-packages/pipenv/patched/safety.zip/click/core.py", line 535, in invoke
  File "/usr/local/lib/python3.6/dist-packages/pipenv/patched/safety.zip/safety/cli.py", line 63, in check
  File "/usr/local/lib/python3.6/dist-packages/pipenv/patched/safety.zip/safety/safety.py", line 126, in check
  File "/usr/local/lib/python3.6/dist-packages/pipenv/patched/safety.zip/safety/safety.py", line 108, in fetch_database
  File "/usr/local/lib/python3.6/dist-packages/pipenv/patched/safety.zip/safety/safety.py", line 79, in fetch_database_url
  File "/usr/local/lib/python3.6/dist-packages/pipenv/patched/safety.zip/requests/api.py", line 72, in get
  File "/usr/local/lib/python3.6/dist-packages/pipenv/patched/safety.zip/requests/api.py", line 58, in request
  File "/usr/local/lib/python3.6/dist-packages/pipenv/patched/safety.zip/requests/sessions.py", line 508, in request
  File "/usr/local/lib/python3.6/dist-packages/pipenv/patched/safety.zip/requests/sessions.py", line 618, in send
  File "/usr/local/lib/python3.6/dist-packages/pipenv/patched/safety.zip/requests/adapters.py", line 521, in send
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='pyup.io', port=443): Read timed out. (read timeout=5)

configure: error: Checking PEP 508 requirements…
Passed!
Checking installed package safety…
```

**Comment by nicowilliams** [comment]
(But I am able to make the docs.  Strange.)

**Comment by amasover** [comment]
I have `pipenv` installed on my system, but get this during the build:

```
Traceback (most recent call last):
  File "build_manpage.py", line 4, in <module>
    from lxml import etree
ModuleNotFoundError: No module named 'lxml'
```

It seems that `lxml` is present on my system:

```
$ pip install --user lxml  
Requirement already satisfied: lxml in /home/aaron/.local/lib/python3.7/site-packages (4.3.2)
```

**Comment by muhmuhten** [comment]
You also need to go into doc and `pipenv sync`, I believe.

**Comment by nicowilliams** [comment]
@muhmuhten ohhhh.  These are not things we can run from `./configure`.  In my `dlopen` branch one of the commits disables docs building by default and exempts `mantests` when docs building is not enabled.

**Comment by nicowilliams** [comment]
Unrelatedly, @fadado, thanks so much for your work on the wiki's sidebar and footer!

**Comment by fadado** [comment]
On 11 Mar 2019 7:14 p.m., "Nico Williams" <notifications@github.com> wrote:

Unrelatedly, @fadado <https://github.com/fadado>, thanks so much for your
work on the wiki's sidebar and footer!


Thanks. I plan to reword soon the wiki home page to acknowledge the new
categorized menu.

JJOR


—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/stedolan/jq/issues/1852#issuecomment-471658525>, or mute
the thread

**Comment by itchyny** [comment]
I think [README.md](https://github.com/jqlang/jq) and [Installation](https://github.com/jqlang/jq/wiki/Installation) describes the `./configure` options in detail, so closing this issue. If you have any documentation improvement, send a Pull Request or edit the Wiki.
