### ISSUE TITLE
build_manpage.py - invalid syntax; and warnings

### ISSUE THREAD

**Issue by pkoppstein** [jqlang/jq#2050]
The following might duplicate, at least in part, another open issue, but I am hoping that an uptodate listing of the warning and error messages that arise when run "make" against the current jq "master" (c084d78c) using Xcode 3.3  might spur an attempt to reduce their number.

(Platform: MacOS Catalina 10.15.2)

```
In file included from src/builtin.c:163:
./src/libm.h:163:10: warning: 'drem' is deprecated: first deprecated in macOS 10.9 [-Wdeprecated-declarations]
LIBM_DDD(drem)
         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/math.h:746:15: note: 'drem' has been
      explicitly marked deprecated here
extern double drem(double, double)
              ^
In file included from src/builtin.c:163:
./src/libm.h:218:9: warning: 'gamma' is deprecated: first deprecated in macOS 10.9 [-Wdeprecated-declarations]
LIBM_DD(gamma)
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/math.h:752:15: note: 'gamma' has been
      explicitly marked deprecated here
extern double gamma(double)
              ^
In file included from src/builtin.c:163:
./src/libm.h:278:9: warning: 'significand' is deprecated: first deprecated in macOS 10.9 - Use `2*frexp( )` or `scalbn(x, -ilogb(x))` instead.
      [-Wdeprecated-declarations]
LIBM_DD(significand)
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/math.h:755:15: note: 'significand' has
      been explicitly marked deprecated here
extern double significand(double)
              ^
src/builtin.c:200:31: warning: implicit declaration of function 'lgamma_r' is invalid in C99 [-Wimplicit-function-declaration]
  jv ret = JV_ARRAY(jv_number(lgamma_r(jv_number_value(input), &sign)));
```

```
src/jv_dtoa_tsd.c:27:41: warning: incompatible pointer types passing 'void (struct dtoa_context *)' to parameter of type
      'void (* _Nullable)(void * _Nonnull)' [-Wincompatible-pointer-types]
  if (pthread_key_create(&dtoa_ctx_key, tsd_dtoa_ctx_dtor) != 0) {
                                        ^~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/pthread.h:366:58: note: passing
      argument to parameter here
int pthread_key_create(pthread_key_t *, void (* _Nullable)(void *));
```
```
  GEN      jq.1
  File "build_manpage.py", line 181
    print('.', dat, sep='\n', file=self.f)
                       ^
```

**Comment by wtlangford** [comment]
What version of python is that? It should be using python3.

**Comment by pkoppstein** [comment]
@wtlangford  asked:
> What version of python is that? It should be using python3.

Presumably it was the system version (/usr/bin/python), which is 2.7.

After installing python3 using homebrew,:

```
$ which python3
/usr/local/bin/python3
$ make
  GEN      jq.1
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
  globals()[__func_name] = __get_hash(__func_name)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
...
```

Thanks.

**Comment by wtlangford** [comment]
It still seems to be using python2 from the filenames in that trace

**Comment by leonid-s-usov** [comment]
on my machine I have followed the instructions from homebrew to make the default python point to python3 by 
```
# python3 as default python
export PATH=/usr/local/opt/python/libexec/bin:$PATH
```

```
> which python
/usr/local/opt/python/libexec/bin/python
> python --version
Python 3.7.6
```

also, please don't forget to install pip3 and prerequisites

**Comment by pkoppstein** [comment]
@leonid-s-usov - Thanks for chiming in.  See below.

@wtlangford and @leonid-s-usuv - I'm sure I could get this to work on my new machine if I worked at it, but my main interest is in making it easy for end-users to install jq (especially on a brand-new machine, as my Catalina is) without too many distractions.   Even with `which python` and `which pip` pointing to version 3, though, things are still not working:

```
$ export PATH=/usr/local/opt/python/libexec/bin:$PATH
$ which python
/usr/local/opt/python/libexec/bin/python
$ python --version
Python 3.7.6
$ which pip
/usr/local/opt/python/libexec/bin/pip
$ pip --version
pip 19.3.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
$ which pip3
/usr/local/bin/pip3
$ make
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
  GEN      jq.1
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
    ...

```

**Comment by leonid-s-usov** [comment]
This looks like a [broken brew installation](https://stackoverflow.com/a/59336112/5171225)

**Comment by pkoppstein** [comment]
@leonid-s-usov wrote:

> This looks like a broken brew installation

After using brew to uninstall python and pipenv, the "GEN jq.1" step still fails with a message: "Failed creating virtual environment".

Here are the details:
```
brew uninstall  --ignore-dependencies python
brew unlink openssl
brew uninstall --force python
brew uninstall pipenv

brew install python
brew install pipenv  # forced installation of python@3.8

$ make
  GEN      jq.1
Warning: the environment variable LANG is not set!
We recommend setting this in ~/.profile (or equivalent) for proper expected behavior.
Creating a virtualenv for this project…
Pipfile: /Users/peak/github/jq/docs/Pipfile
Using /usr/local/Cellar/pipenv/2018.11.26_3/libexec/bin/python3.8 (3.8.1) to create virtualenv…
⠙ Creating virtual environment...Already using interpreter /usr/local/Cellar/pipenv/2018.11.26_3/libexec/bin/python3.8
Using real prefix '/usr/local/Cellar/python@3.8/3.8.1/Frameworks/Python.framework/Versions/3.8'
New python executable in /Users/peak/.local/share/virtualenvs/docs-xIprMhjN/bin/python3.8
Not overwriting existing python script /Users/peak/.local/share/virtualenvs/docs-xIprMhjN/bin/python (you must use /Users/peak/.local/share/virtualenvs/docs-xIprMhjN/bin/python3.8)

✘ Failed creating virtual environment 
[pipenv.exceptions.VirtualenvCreationException]:   File "/usr/local/Cellar/pipenv/2018.11.26_3/libexec/lib/python3.8/site-packages/pipenv/cli/command.py", line 407, in run
...
```
I've also tried with `export PATH=/usr/local/opt/python/libexec/bin:$PATH` but it makes no difference.

**Comment by itchyny** [comment]
@pkoppstein Can you close this issue, or do you have any improvement suggestion? Since macOS Monterey Python2 is not included by default, so it is less likely to hit this situation.

**Comment by pkoppstein** [comment]
Closed as (hopefully) no longer relevant.

**Comment by pkoppstein** [comment]
Closed as (hopefully) no longer relevant.
