### ISSUE TITLE
Some valid scenarios result in malloc_consolidate(): invalid chunk size / Aborted (Linux 64-bit ARM)

### ISSUE THREAD

**Issue by jacobq** [jqlang/jq#2508]
**Describe the bug**

For some reason, if both `-r` and `-a` are used together, some valid JSON inputs (like the one given below) will cause a malloc error, generating an error message and returning a non-zero exit code.

```json
{
  "foo": {
    "bar": 123
  },
  "ethernet": [
    {
      "interface": "eth0",
      "dhcp": {
        "enabled": true
      },
      "static": {
        "enabled": true,
        "address": "10.0.0.2"
      }
    }
  ]
}
```

```
# jq -r -a  .ethernet[0].interface input.json || echo "exited with errors"
"eth0"
malloc_consolidate(): invalid chunk size
Aborted
exited with errors
```

**To Reproduce**

1. Create `input.json` with the following content:
    `{"foo":{"bar":123},"ethernet":[{"interface":"eth0","dhcp":{"enabled":true},"static":{"enabled":true,"address":"10.0.0.2"}}]}`
2. Run `jq -r -a  .ethernet[0].interface input.json` and observe behavior shown above.

**Expected behavior**

I did not expect any memory allocation related problems to manifest when providing valid input, a valid filter, and valid options. If `-r` and `-a` are somehow mutually exclusive then this scenario should be detected and the program should abort with an appropriate message.

**Environment (please complete the following information):**
 - OS and Version: 64-bit Linux (Raspberry Pi OS / Raspian 11: bullseye) (I did not test other platforms)
 - jq version: `jq-1.6` (`apt list` shows `jq/stable,now 1.6-2.1 arm64`)

```
# uname -a
Linux myhostname 5.10.63-v8+ #1488 SMP PREEMPT Thu Nov 18 16:16:16 GMT 2021 aarch64 GNU/Linux

# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Additional context**
I encountered this while working on a real file then tried to strip it down as much as I could without making the error disappear. I do not understand why removing the `foo` property, which gets filtered out, makes the error go away. Seems very much like a bug though. 

<details>
<summary>gdb backtrace (in case it's useful)</summary>

```
# gdb --args jq -a -r ".ethernet[0].interface" tmp.json && echo "OK" || echo "exited with errors"
GNU gdb (Debian 10.1-1.7) 10.1.90.20210103-git
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "aarch64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from jq...
(No debugging symbols found in jq)
(gdb) run
Starting program: /usr/bin/jq -a -r .ethernet\[0\].interface tmp.json
"eth0"
malloc_consolidate(): invalid chunk size

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) backtrace
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x0000007ff7e0cea0 in __GI_abort () at abort.c:79
#2  0x0000007ff7e5a280 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ff7f1e018 "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#3  0x0000007ff7e617dc in malloc_printerr (str=str@entry=0x7ff7f19a60 "malloc_consolidate(): invalid chunk size") at malloc.c:5347
#4  0x0000007ff7e62520 in malloc_consolidate (av=av@entry=0x7ff7f59a98 <main_arena>) at malloc.c:4477
#5  0x0000007ff7e62c48 in _int_free (av=0x7ff7f59a98 <main_arena>, p=0x55555e7c40, have_lock=<optimized out>) at malloc.c:4400
#6  0x0000007ff7f7070c in ?? () from /lib/aarch64-linux-gnu/libjq.so.1
#7  0x0000007ff7f77c78 in jq_teardown () from /lib/aarch64-linux-gnu/libjq.so.1
#8  0x0000005555552810 in ?? ()
#9  0x0000007ff7e0d218 in __libc_start_main (main=0x5555551cd0, argc=5, argv=0x7ffffffbb8, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=<optimized out>) at ../csu/libc-start.c:308
#10 0x00000055555534b4 in ?? ()
Backtrace stopped: not enough registers or memory available to unwind further
(gdb) 
```
</details>

**Comment by emanuele6** [comment]
Fixed in master, and probably related to #2333
