### ISSUE TITLE
Unable to build "master" branch using Python 3.8.17

### ISSUE THREAD

**Issue by SchweinDeBurg** [jqlang/jq#2753]
```
  GEN      jq.1.prebuilt
Traceback (most recent call last):
  File "/home/elijah/.local/share/virtualenvs/docs-bz6x0TBE/lib/python3.8/site-packages/jsonschema_specifications/_core.py", line 8, in <module>
    from importlib.resources import files
ImportError: cannot import name 'files' from 'importlib.resources' (/home/elijah/.local/share/virtualenvs/docs-bz6x0TBE/lib64/python3.8/importlib/resources.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "validate_manual_schema.py", line 2, in <module>
    import jsonschema
  File "/home/elijah/.local/share/virtualenvs/docs-bz6x0TBE/lib/python3.8/site-packages/jsonschema/__init__.py", line 17, in <module>
    from jsonschema.validators import (
  File "/home/elijah/.local/share/virtualenvs/docs-bz6x0TBE/lib/python3.8/site-packages/jsonschema/validators.py", line 19, in <module>
    from jsonschema_specifications import REGISTRY as SPECIFICATIONS
  File "/home/elijah/.local/share/virtualenvs/docs-bz6x0TBE/lib/python3.8/site-packages/jsonschema_specifications/__init__.py", line 7, in <module>
    from jsonschema_specifications._core import _schemas
  File "/home/elijah/.local/share/virtualenvs/docs-bz6x0TBE/lib/python3.8/site-packages/jsonschema_specifications/_core.py", line 10, in <module>
    from importlib_resources import files  # type: ignore
ModuleNotFoundError: No module named 'importlib_resources'
make[2]: *** [Makefile:1940: jq.1.prebuilt] Error 1
make[2]: Leaving directory '/home/elijah/.local/rpmbuild/BUILD/jq'
make[1]: *** [Makefile:1185: all-recursive] Error 1
make[1]: Leaving directory '/home/elijah/.local/rpmbuild/BUILD/jq'
make: *** [Makefile:816: all] Error 2
```

**Comment by itchyny** [comment]
Thanks for reporting.
